const data = {
  produtos: [
    {
      _id: '1',
      nome: 'Macacão Feminino',
      categoria: 'feminino',
      imagem: '/images/calca1.gif',
      preco: 120.50,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 4.0,
      numAvaliacoes: 10,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '2',
      nome: 'Com sobra.',
      categoria: 'calca',
      imagem: '/images/calca2.gif',
      preco: 80.99,
      estoque: 10,
      fornecedor: 'Zé custureiro',
      Avaliacao: 3.0,
      numAvaliacoes: 10,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '3',
      nome: 'Usa quem quer',
      categoria: 'calca',
      imagem: '/images/calca3.gif',
      preco: 180.5,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 4.5,
      numAvaliacoes: 10,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '4',
      nome: 'Sospedaço',
      categoria: 'calca',
      imagem: '/images/calca4.gif',
      preco: 220,
      estoque: 10,
      fornecedor: 'Zé custureiro',
      Avaliacao: 3.0,
      numAvaliacoes: 22,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '5',
      nome: 'Fat Charm',
      categoria: 'camisa',
      imagem: '/images/camisa1.gif',
      preco: 140,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 5.0,
      numAvaliacoes: 110,
      descricao: 'Com tecido extra',
    },
    {
      _id: '6',
      nome: 'Top tall',
      categoria: 'camisa',
      imagem: '/images/camisa2.gif',
      preco: 88.99,
      estoque: 10,
      fornecedor: 'Adidas',
      Avaliacao: 4.0,
      numAvaliacoes: 1,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '7',
      nome: 'Top tall man',
      categoria: 'camisa',
      imagem: '/images/camisa3.gif',
      preco: 99.99,
      estoque: 10,
      fornecedor: 'Adidas',
      Avaliacao: 4.7,
      numAvaliacoes: 110,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '8',
      nome: 'Sonabeca',
      categoria: 'camisa',
      imagem: '/images/camisa4.gif',
      preco: 190,
      estoque: 10,
      fornecedor: 'Zé costureiro',
      Avaliacao: 5.0,
      numAvaliacoes: 310,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '9',
      nome: 'Korona Fashiun',
      categoria: 'camisa',
      imagem: '/images/camisa5.gif',
      preco: 190,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 3.0,
      numAvaliacoes: 1,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '10',
      nome: 'Playboyzynho',
      categoria: 'camisa',
      imagem: '/images/camisa6.gif',
      preco: 90,
      estoque: 10,
      fornecedor: 'Adidas',
      Avaliacao: 2.0,
      numAvaliacoes: 30,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '11',
      nome: 'Alinhado',
      categoria: 'camisa',
      imagem: '/images/camisa7.gif',
      preco: 65.00,
      estoque: 10,
      fornecedor: 'Zé costureiro',
      Avaliacao: 5.0,
      numAvaliacoes: 110,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '12',
      nome: 'Ultra Fino',
      categoria: 'camisa',
      imagem: '/images/camisa8.gif',
      preco: 20,
      estoque: 10,
      fornecedor: 'Zé costureiro',
      Avaliacao: 4.0,
      numAvaliacoes: 304,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '13',
      nome: 'Cat chinese',
      categoria: 'camisa',
      imagem: '/images/camisa9.gif',
      preco: 190,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 2.0,
      numAvaliacoes: 108,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '14',
      nome: 'Litle Baby',
      categoria: 'infantil',
      imagem: '/images/crianca4.gif',
      preco: 19,
      estoque: 10,
      fornecedor: 'Zé costureiro',
      Avaliacao: 2.5,
      numAvaliacoes: 39,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '15',
      nome: 'All two',
      categoria: 'infantil',
      imagem: '/images/infantil1.gif',
      preco: 122,
      estoque: 0,
      fornecedor: 'Nike',
      Avaliacao: 5,
      numAvaliacoes: 139,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '16',
      nome: 'Sapeka Baby',
      categoria: 'infantil',
      imagem: '/images/infantil2.gif',
      preco: 54,
      estoque: 10,
      fornecedor: 'Zé costureiro',
      Avaliacao: 4,
      numAvaliacoes: 639,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '17',
      nome: 'Camp Baby',
      categoria: 'infantil',
      imagem: '/images/infantil3.gif',
      preco: 59,
      estoque: 10,
      fornecedor: 'Zé costureiro',
      Avaliacao: 5,
      numAvaliacoes: 139,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '18',
      nome: 'Sokerser',
      categoria: 'femenina',
      imagem: '/images/vestido1.gif',
      preco: 119,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 4,
      numAvaliacoes: 209,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '19',
      nome: 'Sapatão',
      categoria: 'calcados',
      imagem: '/images/sapato1.gif',
      preco: 87,
      estoque: 10,
      fornecedor: 'Adidas',
      Avaliacao: 5.0,
      numAvaliacoes: 369,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '20',
      nome: 'Vaikair',
      categoria: 'calcados',
      imagem: '/images/sapato2.gif',
      preco: 187,
      estoque: 0,
      fornecedor: 'Adidas',
      Avaliacao: 4.0,
      numAvaliacoes: 69,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '21',
      nome: 'VaikairTwo',
      categoria: 'calcados',
      imagem: '/images/sapato3.gif',
      preco: 97,
      estoque: 10,
      fornecedor: 'Adidas',
      Avaliacao: 5,
      numAvaliacoes: 1369,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '22',
      nome: 'Trankilo basic',
      categoria: 'calcados',
      imagem: '/images/sapato4.gif',
      preco: 102,
      estoque: 10,
      fornecedor: 'Nike',
      Avaliacao: 4.5,
      numAvaliacoes: 9,
      descricao: 'Vai ficar muito bem em você',
    },
    {
      _id: '23',
      nome: 'SokerSer',
      categoria: 'calcados',
      imagem: '/images/sapato5.gif',
      preco: 51,
      estoque: 0,
      fornecedor: 'Adidas',
      Avaliacao: 3.0,
      numAvaliacoes: 1369,
      descricao: 'Vai ficar muito bem em você',
    },
  ]
}

export default data;
